import { numeric, pgTable, text, timestamp, uniqueIndex, uuid, date } from "drizzle-orm/pg-core";
import { reportStatusEnum, wasteTypeEnum } from "./enums.js";
import { wasteEvents } from "./waste-events.js";
import { workspaces } from "./workspaces.js";

/**
 * Weekly report metadata (email via Resend + pdf-lib PDF, generated by the
 * worker). One row per workspace per week; content fields are snapshots so
 * past reports don't change when detectors improve.
 */
export const reports = pgTable(
  "reports",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    workspaceId: uuid("workspace_id")
      .notNull()
      .references(() => workspaces.id, { onDelete: "cascade" }),
    /** ISO week bounds (week_start is a Monday), stored as calendar dates. */
    weekStart: date("week_start", { mode: "string" }).notNull(),
    weekEnd: date("week_end", { mode: "string" }).notNull(),
    totalSpendUsd: numeric("total_spend_usd", {
      precision: 14,
      scale: 8,
      mode: "number",
    }).notNull(),
    dollarsWasted: numeric("dollars_wasted", {
      precision: 14,
      scale: 8,
      mode: "number",
    }).notNull(),
    /** dollars_wasted / total_spend for the week (0..1). */
    wasteRate: numeric("waste_rate", {
      precision: 8,
      scale: 6,
      mode: "number",
    }).notNull(),
    topWasteType: wasteTypeEnum("top_waste_type"),
    biggestEventId: uuid("biggest_event_id").references(() => wasteEvents.id, {
      onDelete: "set null",
    }),
    topFix: text("top_fix"),
    /**
     * Where the generated PDF bytes live (worker-local path under
     * REPORT_OUTPUT_DIR). Stored regardless of email delivery status.
     */
    pdfPath: text("pdf_path"),
    status: reportStatusEnum("status").notNull().default("generated"),
    emailSentAt: timestamp("email_sent_at", { withTimezone: true, mode: "date" }),
    createdAt: timestamp("created_at", { withTimezone: true, mode: "date" })
      .notNull()
      .defaultNow(),
  },
  (t) => [uniqueIndex("reports_workspace_week_idx").on(t.workspaceId, t.weekStart)],
);

export type ReportRow = typeof reports.$inferSelect;
export type NewReportRow = typeof reports.$inferInsert;
